name: Deploy to shinyapps.io
on:

   # run on request (via button in actions menu)
  workflow_dispatch:
      
jobs:
  deploy:
    name: Deploy to shinyapps

    # allow skipping deployment for commits containing '[automated]' or '[no-deploy]' in the commit message
    if: "!contains(github.event.head_commit.message, '[automated]') && !contains(github.event.head_commit.message, '[no-deploy]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        uses: BDSI-Utwente/shinyapps-deploy-github-action@v1
        with:
          # account and application name (https://hydrotoxy.shinyapps.io/anzg-metal-tool)
          appName: anzg-metal-tool
          accountName: hydrotoxy

          # token and secret obtained from https://www.shinyapps.io/admin/#/tokens
          accountToken: ${{ secrets.EB8CB78E5D36D6CB5595D9572E4C12D4 }}
          accountSecret: ${{ secrets.fMFNQLN+twwkeNXIpaS8mjGoh0pQe2t9gEiEvhqT }}
